/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.2.2] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */

/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnTimer_tmr_500_500( );
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
/* End BUSMASTER Function Wrapper Prototype  */


/* Start BUSMASTER generated function - OnTimer_tmr_500_500 */
void OnTimer_tmr_500_500( )
{
/* TODO */
/*CLOSED -> 1 & OPEN ->0 */
door_st ds;
ds.FL = 1;
ds.FR = 1;
ds.RL = 1;
ds.RR = 0;
SendMsg(ds);

}/* End BUSMASTER generated function - OnTimer_tmr_500_500 */
