/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.2.2] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */

/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
void OnMsgName_door_st(door_st RxMsg);
GCC_EXTERN void GCC_EXPORT OnMsgName_door_st_Wrapper(STCAN_MSG RxMsg);
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
void OnMsgName_door_st_Wrapper(STCAN_MSG RxMsg){ OnMsgName_door_st(&RxMsg); }
/* End BUSMASTER Function Wrapper Prototype  */


/* Start BUSMASTER generated function - OnMsgName_door_st */
void OnMsgName_door_st(door_st RxMsg)
{
/* TODO */
DB_Lamp lmp;
if(RxMsg.FL==0 || RxMsg.FR==0 || RxMsg.RL==0 || RxMsg.RR==0)
{
	lmp.lamp_st =1;//on LED
}
else
{
	lmp.lamp_st = 0;//off LED
}
SendMsg(lmp);
}/* End BUSMASTER generated function - OnMsgName_door_st */
